#!/bin/sh /etc/rc.common

START=99

EXTRA_COMMANDS="status"
EXTRA_HELP="        status          Check xray status"

TABLE_NUM=100

SUBNET_LAN="192.168.0.0/16"
SUBNET_RES="10.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 172.16.0.0/12 192.0.0.0/24 224.0.0.0/3"

TPROXY_MARK=255
TPROXY_PORT=12345

XRAY_USER="xray"
XRAY_GID=10000

XRAY_BINARY="/usr/bin/xray"
XRAY_ASSETS="/usr/share/xray"
XRAY_CONFIG="/etc/xray/config.json"

add_routing_policy() {
    ip rule add fwmark $TPROXY_MARK table $TABLE_NUM
    ip route add local default dev lo table $TABLE_NUM
}

add_iptables_prerouting_rules() {
    iptables -t mangle -N XRAY

    iptables -t mangle -A XRAY ! -s $SUBNET_LAN -j RETURN

    for SUBNET in $SUBNET_RES; do iptables -t mangle -A XRAY -d $SUBNET -j RETURN; done

    iptables -t mangle -A XRAY -d $SUBNET_LAN -p tcp ! --dport 53 -j RETURN
    iptables -t mangle -A XRAY -d $SUBNET_LAN -p udp ! --dport 53 -j RETURN

    iptables -t mangle -A XRAY -p tcp -j TPROXY --on-port $TPROXY_PORT --tproxy-mark $TPROXY_MARK
    iptables -t mangle -A XRAY -p udp -j TPROXY --on-port $TPROXY_PORT --tproxy-mark $TPROXY_MARK

    iptables -t mangle -A PREROUTING -j XRAY
}

add_iptables_output_rules() {
    iptables -t mangle -N XRAY_MASK

    iptables -t mangle -A XRAY_MASK -m owner --gid-owner $XRAY_GID -j RETURN

    for SUBNET in $SUBNET_RES; do iptables -t mangle -A XRAY_MASK -d $SUBNET -j RETURN; done

    iptables -t mangle -A XRAY_MASK -d $SUBNET_LAN -p tcp ! --dport 53 -j RETURN
    iptables -t mangle -A XRAY_MASK -d $SUBNET_LAN -p udp ! --dport 53 -j RETURN

    iptables -t mangle -A XRAY_MASK -j MARK --set-mark $TPROXY_MARK

    iptables -t mangle -A OUTPUT -p tcp -j XRAY_MASK
    iptables -t mangle -A OUTPUT -p udp -j XRAY_MASK
}

add_xray_user() {
    grep -qw $XRAY_USER /etc/passwd || echo "$XRAY_USER:x:0:$XRAY_GID:::/bin/false" >> /etc/passwd
}

start_xray() {
    add_routing_policy

    add_iptables_prerouting_rules
    add_iptables_output_rules

    add_xray_user

    ulimit -SHn 1000000
    sudo -u $XRAY_USER env XRAY_LOCATION_ASSET=$XRAY_ASSETS $XRAY_BINARY -c $XRAY_CONFIG >/dev/null 2>&1 &
}

start() {
    if pgrep -x $XRAY_BINARY >/dev/null 2>&1; then
        echo "xray is already running"
        return 0
    fi

    start_xray
}

del_routing_policy() {
    ip rule del fwmark $TPROXY_MARK table $TABLE_NUM
    ip route del local default dev lo table $TABLE_NUM
}

del_iptables_prerouting_rules() {
    iptables -t mangle -D PREROUTING -j XRAY

    iptables -t mangle -F XRAY
    iptables -t mangle -X XRAY
}

del_iptables_output_rules() {
    iptables -t mangle -D OUTPUT -p tcp -j XRAY_MASK
    iptables -t mangle -D OUTPUT -p udp -j XRAY_MASK

    iptables -t mangle -F XRAY_MASK
    iptables -t mangle -X XRAY_MASK
}

del_xray_user() {
    grep -qw $XRAY_USER /etc/passwd && sed -i "/^$XRAY_USER:/d" /etc/passwd
}

stop_xray() {
    del_routing_policy

    del_iptables_prerouting_rules
    del_iptables_output_rules

    del_xray_user

    killall xray
}

stop() {
    stop_xray
}

status() {
    if pgrep -x $XRAY_BINARY >/dev/null 2>&1; then
        echo "xray is running"
    else
        echo "xray is stopped"
    fi
}
